import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>XILEF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="form-container">
          <div className="headline">
            <div className="brand">xilef
            </div>	
            <div>
              <p>ihre Randomisierungssoftware</p>
            </div>
            <div className="hr-container">
              <p className="hr-vert-small"></p>
            </div>	
              <Link href ="">
                <button className ="button-long" type="submit"><p>Bei bestehener Studie einloggen(unfertig)</p></button>
              </Link> 
              <div className="hr-container">
                <p className="hr-vert-small"></p>
              </div>	
              <Link href ="/create">  
                <button className ="button-long" type="submit"><p>eine neue Studie anlegen</p></button>   
            </Link> 
          </div>  
          </div>
    </>
  )
}
